site_name: Sonata Docs
site_description: Docs for Sonata, an all-in-one Luau toolkit
site_url: https://sonata.5418.org/docs/
repo_url: https://github.com/Sonata-CLI/sonata
repo_name: Sonata-CLI/sonata
copyright: Copyright &copy; 2026 - Sonata by Loopy5418

theme:
    name: material

    font:
        text: Inter Tight
        code: Fragment Mono

    icon:
        repo: fontawesome/brands/github 

    logo: assets/sonata_default.svg
    favicon: assets/sonata_default.svg

    features:
        - navigation.tabs
        - navigation.sections
        - navigation.top
        - navigation.instant
        - navigation.instant.progress
        - navigation.path
        - navigation.indexes
        - navigation.expand
        - toc.follow
        - search.suggest
        - content.code.copy

    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep purple
          accent: deep purple
          toggle:
            icon: material/weather-sunny
            name: Switch to dark mode

        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep purple
          accent: deep purple
          toggle:
            icon: material/weather-night
            name: Switch to light mode

extra_css:
    - stylesheets/extra.css

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Sonata-CLI
        
        - icon: fontawesome/brands/discord
          link: https://discord.gg/kGVWCdVHvW

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - attr_list

nav:
    - Home: index.md
    - Guide: guide/index.md
    - API:
        - Overview: api/index.md
        - Source:
            - api/source/index.md
            - Namespaces:
                - sonata: api/source/namespaces/sonata.md
                - cli: api/source/namespaces/cli.md
                - util: api/source/namespaces/util.md
        - Module:
            - api/module/index.md